import { Inter } from 'next/font/google'
import './globals.css'

//Internal
import { NavBar, Footer } from './Components';

import { Web3Modal } from "../../Context/Web3Modal";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <NavBar></NavBar>
        </header>
        <Web3Modal>{children}</Web3Modal>
        <Footer></Footer>
        </body>
    </html>
  )
}
